'use client'

import { GlobalStyles } from '@/styles/global'

import TheSidebar from '@/components/TheSidebar'
import BaseContainer from '@/components/BaseContainer'

import SIDEBAR_DATA from '@/mocks/sidebar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <GlobalStyles />
      <body>
      <TheSidebar data={SIDEBAR_DATA}/>
      <BaseContainer>
        {children}
      </BaseContainer>
      </body>
    </html>
  )
}
