"use client"

import { GlobalStyles } from '@/styles/global'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <GlobalStyles />
      <body>{children}</body>
    </html>
  )
}
